services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
      - ./server/.env.docker.development
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network
    ports:
      - 3000:3000
      - 4000:4000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - app-network
    ports:
      - 5173:80

volumes:
  redis-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
